common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5000
    log:
        conf: "logging_dev.yaml"
    aws:
        url: "https://{}.s3-ap-northeast-1.amazonaws.com/{}"
    local_photo:
        dir: "local_uploads"
        url: "/student/local_uploads/{}"
    mm_division:
        file_path: "/../../data/mm_division/division.json"
    default_address:
        division: "ayeyarwady"
        district: "maubin"
        township: "nyaungdone"
        street_address: "တိုက်သစ်ကျောင်း"
postgres:
    url: "postgresql://"
    host: "localhost"
    port: 5432
    user: "thingaha"
    password: "thingaha"
    db: "thingaha_dev"
